apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveryservice-deployment
  namespace: deliveryservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - name: deliveryservice
        image: sabafadhl/deliveryservice:latest
        ports:
        - containerPort: 8080
