name: Docker Publish
on:
  pull_request:
    branches: [ master, feat/actions  ]
  push:
    branches: [ feat/actions ]

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Delivery_Service
          file: ./Delivery_Service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/deliveryservice:latest  # Please change the username here