name: Docker Publish
on:
  pull_request:
    branches: [ master, feat/actions  ]
  push:
    branches: [ feat/actions ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Delivery_Service
        file: Delivery_Service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/deliveryservice:test

